CREATE TABLE IF NOT EXISTS ACTOR  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20),
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MOVIE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(20) NOT NULL,
  GENRE VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(255),
  ID_MAIN_ACTOR BIGINT NOT NULL,
  FOREIGN KEY(ID_MAIN_ACTOR) REFERENCES ACTOR(ID),
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MOVIE_SEC_ACTORS(
ID_MOVIE BIGINT NOT NULL,
ID_ACTOR BIGINT NOT NULL,
PRIMARY KEY (ID_MOVIE,ID_ACTOR),
FOREIGN KEY(ID_MOVIE) REFERENCES MOVIE(ID),
FOREIGN KEY(ID_ACTOR) REFERENCES ACTOR(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS APP_USER(
ID BIGINT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS REVIEW(
ID BIGINT NOT NULL AUTO_INCREMENT,
ID_MOVIE BIGINT NOT NULL,
ID_REVIEWER BIGINT NOT NULL,
MARK SMALLINT NOT NULL,
REVIEW_COMMENT VARCHAR(255),
PRIMARY KEY (ID),
FOREIGN KEY(ID_MOVIE) REFERENCES MOVIE(ID),
FOREIGN KEY(ID_REVIEWER) REFERENCES APP_USER(ID)
) ENGINE=InnoDB;